---
platform: linux

image_resource:
  type: docker-image
  source: {repository: golang}

inputs:
- name: multibranch
  path: gopath/src/github.com/insolar/assured-ledger/ledger-core/v2

caches:
- path: depspath/
- path: gopath/pkg/

params:
  GIT_BRANCH: master

run:
  path: gopath/src/github.com/insolar/assured-ledger/ledger-core/v2/ci/test-net
