name: common
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 2,4,6 * * *'
env:
  GO_VERSION: 1.14
  CI_GOMAXPROCS: 0
  INSOLAR_LOG_LEVEL: warn
jobs:
  unit-tests:
    name: unit-tests
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/work/insolar/insolar/go
    steps:
      - name: checkout code
        uses: actions/checkout@master
        with:
          path: go/src/github.com/insolar/insolar
      - name: set up go ${{env.GO_VERSION}}
        uses: actions/setup-go@v1
        with:
          go-version: ${{env.GO_VERSION}}
      - name: add bin to path
        run: echo "::add-path::${{env.GOPATH}}/bin"
      - name: test_prepare
        run: |
          go mod download
          make pre-build build
        working-directory: ${{env.GOPATH}}/src/github.com/insolar/insolar
      - name: test_unit
        run: make test_unit
        working-directory: ${{env.GOPATH}}/src/github.com/insolar/insolar
  slow-tests:
    name: slow-tests
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/work/insolar/insolar/go
    steps:
      - name: checkout code
        uses: actions/checkout@master
        with:
          path: go/src/github.com/insolar/insolar
      - name: set up go ${{env.GO_VERSION}}
        uses: actions/setup-go@v1
        with:
          go-version: ${{env.GO_VERSION}}
      - name: add bin to path
        run: echo "::add-path::${{env.GOPATH}}/bin"
      - name: test_prepare
        run: |
          go mod download
          make pre-build build
        working-directory: ${{env.GOPATH}}/src/github.com/insolar/insolar
      - name: test_slow
        run: make test_slow
        working-directory: ${{env.GOPATH}}/src/github.com/insolar/insolar
